### ISSUE TITLE
failed to look up user vault when hashicorp_installation_method: manual

### ISSUE THREAD

**Issue by patsevanton** [robertdebock/ansible-role-vault#10]
## Describe the bug
failed to look up user vault when hashicorp_installation_method: manual

## Playbook

```yaml
---
- name: prepare
  hosts: vault_raft_servers
  become: true
  become_method: sudo
  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=true cache_valid_time=600
      when: ansible_os_family == 'Debian'
    - name: Update /etc/hosts
      blockinfile:
        path: /etc/hosts
        block: |
          {% for host in groups['all'] %}
          {{ hostvars[host].ansible_host }} {{ host }}
          {% endfor %}
  roles:
    - role: robertdebock.core_dependencies
    - role: robertdebock.hashicorp
      hashicorp_installation_method: manual
      hashicorp_products:
        - name: vault
          version: "1.9.4"
          type: oss

- name: Assemble Vault cluster
  hosts: vault_raft_servers
  any_errors_fatal: true
  become: true
  become_user: root
  gather_facts: true
  debugger: on_failed
  roles:
    - robertdebock.vault
  vars:
    vault_show_unseal_information: yes
    vault_install_package: no
    vault_store_root_token: yes
    vault_make_backup: no
    vault_leader: "{{ hostvars[groups['vault_instances'][0]].ansible_host }}"
    vault_listeners:
      - name: tcp
        address: "127.0.0.1:8200"
        cluster_address: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:8201"
        tls_disable: "true"

      - name: tcp
        address: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:8200"
        cluster_address: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:8201"
        tls_disable: "true"
    vault_log_level: "debug"
    vault_disable_clustering: "false"
    vault_api_addr: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:8200"
    vault_cluster_addr: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:8201"
```

## Output

```
TASK [robertdebock.vault : create vault storage path] **********************************************************************************************************
Saturday 07 May 2022  22:40:10 +0600 (0:00:00.026)       0:00:18.880 **********
failed: [vault1] (item=/vault/data) => changed=false
  ansible_loop_var: item
  gid: 0
  group: root
  item:
    name: raft
    node_id: vault1
    path: /vault/data
  mode: '0755'
  msg: 'chown failed: failed to look up user vault'
  owner: root
  path: /vault
  size: 4096
  state: directory
  uid: 0
[vault1] TASK: robertdebock.vault : create vault storage path (debug)> failed: [vault0] (item=/vault/data) => changed=false
  ansible_loop_var: item
  gid: 0
  group: root
  item:
    name: raft
    node_id: vault0
    path: /vault/data
  mode: '0755'
  msg: 'chown failed: failed to look up user vault'
  owner: root
  path: /vault
  size: 4096
  state: directory
  uid: 0
failed: [vault2] (item=/vault/data) => changed=false
  ansible_loop_var: item
  gid: 0
  group: root
  item:
    name: raft
    node_id: vault2
    path: /vault/data
  mode: '0755'
  msg: 'chown failed: failed to look up user vault'
  owner: root
  path: /vault
  size: 4096
  state: directory
  uid: 0
```

## Environment

- Control node OS: [e.g. Debian 9] (`cat /etc/os-release`)
```
NAME="Ubuntu"
VERSION="20.04 LTS (Focal Fossa)"
```
- Control node Ansible version: [e.g. 2.9.1] (`ansible --version`)
```
ansible [core 2.12.4]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /home/user/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.8.10 (default, Mar 15 2022, 12:22:08) [GCC 9.4.0]
  jinja version = 3.1.2
  libyaml = True
```
- Managed node OS: [e.g. CentOS 7] (`cat /etc/os-release`)
```
NAME="Ubuntu"
VERSION="20.04 LTS (Focal Fossa)"
```

Inventory
```
all:
  children:
    vault_raft_servers:
      hosts:
        vault0:
          ansible_host: xxxxx
        vault1:
          ansible_host: xxxx
        vault2:
          ansible_host: xxxx
```

Check user and group
```
root@vault0:~# cat /etc/passwd  | grep vault
root@vault0:~# cat /etc/group  | grep vault
root@vault0:~#
```

**Comment by patsevanton** [comment]
Fixed by
```
  post_tasks:
    - name: Ensure group "vault" exists
      ansible.builtin.group:
        name: vault
        state: present
    - name: Add the user 'vault' and a primary group of 'vault'
      ansible.builtin.user:
        name: vault
        home: /home/vault
        shell: /bin/false
        group: vault
```

Could you review PR with add "Add the user 'vault' and a primary group of 'vault'" if hashicorp_installation_method: manual ?
