### ISSUE TITLE
parameters recovery_shares,recovery_threshold not applicable to seal type shamir

### ISSUE THREAD

**Issue by CyberSeppi** [robertdebock/ansible-role-vault#12]
Hi there,

getting this error on a AWS EC2 instance with Ubuntu focal installed:

TASK [robertdebock.vault : initialize vault on leader] *************************
fatal: [vault_instance]: FAILED! => {"changed": true, "cmd": ["vault", "operator", "init", "-key-shares=5", "-key-threshold=3", "-format=yaml"], "delta": "0:00:00.049334", "end": "2022-10-15 19:31:51.442021", "msg": "non-zero return code", "rc": 2, "start": "2022-10-15 19:31:51.392687", "stderr": "Error initializing: Error making API request.\n\nURL: PUT http://127.0.0.1:8200/v1/sys/init\nCode: 400. Errors:\n\n* parameters recovery_shares,recovery_threshold not applicable to seal type shamir", "stderr_lines": ["Error initializing: Error making API request.", "", "URL: PUT http://127.0.0.1:8200/v1/sys/init", "Code: 400. Errors:", "", "* parameters recovery_shares,recovery_threshold not applicable to seal type shamir"], "stdout": "", "stdout_lines": []}

Playbook is nothing especially complex:
```

- hosts: all
  become: true
  become_method: sudo
 

  tasks:

    - name: Include System Variables
      ansible.builtin.include_vars:
        dir: '../vars'

    - name: Insert Proxy Environment
      ansible.builtin.lineinfile:
        dest: "/etc/environment"
        state: present
        create: 'yes'
        regexp: "^{{ item.key }}="
        line: "{{ item.key }}={{ item.value }}"
      loop: "{{ proxy_env }}"      

    - name: Create vault group
      ansible.builtin.group:
        name: 'vault'
        state: present

    - name: Create vault user
      ansible.builtin.user:
        name: 'vault'
        group: 'vault'
        shell: '/bin/bash'
        state: present

    - name: Include Role Vault
      ansible.builtin.include_role:
        name: '{{ outer_item }}'
      loop:
        - 'robertdebock.bootstrap'
        - 'robertdebock.core_dependencies'
        - 'robertdebock.hashicorp'
      loop_control:
        loop_var: outer_item        

    - name: Include Role Vault
      ansible.builtin.include_role:
        name: 'robertdebock.vault'
      vars:
        vault_disable_clustering: "true"
        vault_log_level: "debug"

```
