### ISSUE TITLE
Static path definition for tls in binary.yml and vault.hcl

### ISSUE THREAD

**Issue by Kaedo** [robertdebock/ansible-role-vault#15]
## Describe the bug

When using a binary installation method with this role and changing the _vault_data_directory_ 
to something else then "/opt/" the execution will fail, due to static definition of the TLS path in binary.yaml and vault.hcl

## Playbook

```yaml
---
- name: Install hashicorp vault via roles
  hosts: pikvm
  pre_tasks:
    - ansible.builtin.shell: rw
  roles:
    - role: robertdebock.bootstrap
    - role: robertdebock.core_dependencies
    - role: robertdebock.hashicorp
    - role: ansible-role-vault 
      vars:
        - vault_type: oss
        - vault_architecture: "arm"
        - ansible_architecture: "arm"
        - vault_version: "1.13.1"
        - vault_package_release: "1"
        - vault_installation_method: "binary"
        - vault_download_path: "/vault/vault-{{ vault_version }}"
        - vault_path: "/vault"
        - vault_user: vault
        - vault_group: vault
        - vault_user_shell: /bin/false
        - vault_data_directory: "/vault"
```

## Output
- The output was that the tls certificate could not be created because the path /opt/vault/tls was not found

## Root cause

```bash
[nix-shell:~/vault]$ ag /opt/

roles/ansible-role-vault/files/vault.hcl
9:  path = "/opt/vault/data"
26:  tls_cert_file = "/opt/vault/tls/tls.crt"
27:  tls_key_file  = "/opt/vault/tls/tls.key"

roles/ansible-role-vault-fixed-vault-path-setting/files/vault.hcl
9:  path = "/opt/vault/data"
26:  tls_cert_file = "/opt/vault/tls/tls.crt"
27:  tls_key_file  = "/opt/vault/tls/tls.key"

```

## Fix
- Replace the path `/opt/vault/` with `{{ vault_data_directory }}` and create a jinja template for the vault.hcl file
- I am going to create a pull request in a second

## Environment  
- Control node OS:
```
NAME="Arch Linux ARM"
PRETTY_NAME="Arch Linux ARM"
ID=archarm
ID_LIKE=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinuxarm.org/"
DOCUMENTATION_URL="https://archlinuxarm.org/wiki"
SUPPORT_URL="https://archlinuxarm.org/forum"
BUG_REPORT_URL="https://github.com/archlinuxarm/PKGBUILDs/issues"
LOGO=archlinux-logo
```

- Control node Ansible version:
```
ansible [core 2.14.0]
  config file = /home/.../vault/ansible.cfg
  configured module search path = ['/home/.../.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /nix/store/dbmlg0iq0b4w7s5nm8is0n56g2d95r4r-python3.10-ansible-core-2.14.0/lib/python3.10/site-packages/ansible
  ansible collection location = /home/.../.ansible/collections:/usr/share/ansible/collections
  executable location = /nix/store/dbmlg0iq0b4w7s5nm8is0n56g2d95r4r-python3.10-ansible-core-2.14.0/bin/ansible
  python version = 3.10.9 (main, Dec  6 2022, 18:44:57) [GCC 11.3.0] (/nix/store/al6g1zbk8li6p8mcyp0h60d08jaahf8c-python3-3.10.9/bin/python3.10)
  jinja version = 3.1.2
  libyaml = True
```

- Managed node OS:
```
NAME="Arch Linux ARM"
PRETTY_NAME="Arch Linux ARM"
ID=archarm
ID_LIKE=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinuxarm.org/"
DOCUMENTATION_URL="https://archlinuxarm.org/wiki"
SUPPORT_URL="https://archlinuxarm.org/forum"
BUG_REPORT_URL="https://github.com/archlinuxarm/PKGBUILDs/issues"
LOGO=archlinux-logo
```

## Thx
Despite this little issue, your role worked out of the box and was clear to apply, so thank you very much for your work.
